// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoDetect():Promise<string>;

export function GeneratePortTreeForIP(arg1:string):Promise<Array<main.PortTree>>;

export function GeneratePortTreesByCIDR(arg1:string):Promise<Array<main.PortTree>>;

export function PingIPsByCIDR(arg1:string):Promise<Array<string>>;

export function PingPort(arg1:string,arg2:number):Promise<boolean>;
