// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoDetect() {
  return window['go']['main']['App']['AutoDetect']();
}

export function GeneratePortTreeForIP(arg1) {
  return window['go']['main']['App']['GeneratePortTreeForIP'](arg1);
}

export function GeneratePortTreesByCIDR(arg1) {
  return window['go']['main']['App']['GeneratePortTreesByCIDR'](arg1);
}

export function PingIPsByCIDR(arg1) {
  return window['go']['main']['App']['PingIPsByCIDR'](arg1);
}

export function PingPort(arg1, arg2) {
  return window['go']['main']['App']['PingPort'](arg1, arg2);
}
